/* eslint-disable react/no-unescaped-entities */
/* eslint-disable @next/next/no-sync-scripts */

export default function Head() {
  return (
    <>
      <title>SiteStats</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
